### ISSUE TITLE
Warning from Browserslist

### ISSUE THREAD

**Issue by novemberkilo** [tmattio/opam-tailwindcss#2]
Thanks for this project :) 

Since adopting this in `ocaml-ci` we're seeing the following message when we build the project

```
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```

Following the directions does not do much - the warning continues to occur. Wondering if this is because `caniuse-lite` requires updating here?

**Comment by tmattio** [comment]
Hi @novemberkilo!

I just upgraded to the latest tailwindcss version ([3.2.4](https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.2.4)). Do you still have the warning using the latest commit?

**Comment by MisterDA** [comment]
I confirm that using latest tailwind fixes this warning.

**Comment by novemberkilo** [comment]
Thanks @tmattio for the quick turnaround. Much appreciated :)
